/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ssc.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.ssc.block.*;
import net.mcreator.ssc.Ssc14Mod;

import java.util.function.Function;

public class Ssc14ModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(Ssc14Mod.MODID);
	public static final DeferredBlock<Block> ROD_FLOOR;
	public static final DeferredBlock<Block> SHEATHING;
	public static final DeferredBlock<Block> TITLE_STEEL;
	public static final DeferredBlock<Block> STEEL_WALL;
	public static final DeferredBlock<Block> WALL_CARCASE;
	public static final DeferredBlock<Block> UPER_SHEATHING;
	public static final DeferredBlock<Block> ROD_UP_FLOOR;
	public static final DeferredBlock<Block> BASE_AIRLOCK_D_1;
	public static final DeferredBlock<Block> UP_TITLE;
	public static final DeferredBlock<Block> CONSOLE_OF_ID;
	public static final DeferredBlock<Block> BASE_WINDOW;
	public static final DeferredBlock<Block> PORTABLE_SHEATER;
	public static final DeferredBlock<Block> PLASTEEL_WALL;
	public static final DeferredBlock<Block> PLASTEEL_WALL_CARCASE;
	public static final DeferredBlock<Block> TITLE_DARK;
	public static final DeferredBlock<Block> APC;
	public static final DeferredBlock<Block> PODSTATION;
	public static final DeferredBlock<Block> DEBU_GGENERATOR;
	public static final DeferredBlock<Block> LAMP;
	public static final DeferredBlock<Block> AIRLOCK_UP_PLUG;
	public static final DeferredBlock<Block> AIRLOCK_UP_PLUG_OPEN;
	public static final DeferredBlock<Block> TITLE_STEEL_DIAGONAL_MINI;
	public static final DeferredBlock<Block> TITLE_STEEL_DIAGONAL;
	public static final DeferredBlock<Block> UP_TITLE_STEEL;
	public static final DeferredBlock<Block> UP_TITLE_DARK;
	public static final DeferredBlock<Block> TITLE_STEEL_MINI;
	public static final DeferredBlock<Block> TITLE_STEEL_MONO;
	public static final DeferredBlock<Block> TITLE_STEEL_OFFSET;
	public static final DeferredBlock<Block> TITLE_STEEL_PAVEMENT;
	public static final DeferredBlock<Block> TITLE_STEEL_HERRINGBONE;
	public static final DeferredBlock<Block> TITLE_PLASTIC;
	public static final DeferredBlock<Block> TITLE_DARK_DIAGONAL_MINI;
	public static final DeferredBlock<Block> TITLE_DARK_DIAGONAL;
	public static final DeferredBlock<Block> TITLE_DARK_MINI;
	public static final DeferredBlock<Block> TITLE_DARK_MONO;
	public static final DeferredBlock<Block> TITLE_DARK_OFFSET;
	public static final DeferredBlock<Block> TITLE_DARK_PAVEMENT;
	public static final DeferredBlock<Block> TITLE_DARK_PAVEMENT_VERTICAL;
	public static final DeferredBlock<Block> TITLE_DARK_HERRINGBONE;
	public static final DeferredBlock<Block> TITLE_DARK_PLASTIC;
	public static final DeferredBlock<Block> SMES;
	public static final DeferredBlock<Block> TECH_LAMP;
	public static final DeferredBlock<Block> ARMORED_WINDOW;
	public static final DeferredBlock<Block> DEBUG_LAMP;
	public static final DeferredBlock<Block> DEBUG_TECH_LAMP;
	public static final DeferredBlock<Block> GRILLE;
	public static final DeferredBlock<Block> BROKEN_GRILLE;
	public static final DeferredBlock<Block> ASTEROID_STONE_BASE;
	public static final DeferredBlock<Block> ASTEROID_STONE_IRON;
	public static final DeferredBlock<Block> ASTEROID_STONE_QUARTZ;
	public static final DeferredBlock<Block> ASTEROID_STONE_COAL;
	public static final DeferredBlock<Block> ASTEROID_STONE_GOLD;
	public static final DeferredBlock<Block> ASTEROID_STONE_PLASMA;
	public static final DeferredBlock<Block> ASTEROID_STONE_SILVER;
	public static final DeferredBlock<Block> ASTEROID_STONE_URAN;
	public static final DeferredBlock<Block> ASTEROID_STONE_DIAMOND;
	public static final DeferredBlock<Block> CAVE_FLOOR_1;
	public static final DeferredBlock<Block> CAVE_FLOOR_2;
	public static final DeferredBlock<Block> CAVE_FLOOR_3;
	public static final DeferredBlock<Block> CAVE_FLOOR_4;
	public static final DeferredBlock<Block> CAVE_FLOOR_5;
	public static final DeferredBlock<Block> CAVE_FLOOR_6;
	public static final DeferredBlock<Block> CAVE_FLOOR_7;
	public static final DeferredBlock<Block> GRAVITY_GENERATOR;
	public static final DeferredBlock<Block> TITLE_WHITE;
	public static final DeferredBlock<Block> TITLE_WHITE_DIAGONAL_MINI;
	public static final DeferredBlock<Block> CATWALK_FLOOR;
	public static final DeferredBlock<Block> TITLE_WHITE_DIAGONAL;
	public static final DeferredBlock<Block> TITLE_WHITE_HERRINGBONE;
	public static final DeferredBlock<Block> TITLE_WHITE_MINI;
	public static final DeferredBlock<Block> TITLE_WHITE_MONO;
	public static final DeferredBlock<Block> TITLE_WHITE_OFFSET;
	public static final DeferredBlock<Block> TITLE_WHITE_PAVEMENT;
	public static final DeferredBlock<Block> TITLE_WHITE_PAVEMENT_VERTICAL;
	public static final DeferredBlock<Block> TITLE_WHITE_PLASTIC;
	public static final DeferredBlock<Block> C_4;
	public static final DeferredBlock<Block> MACHINE_FRAME;
	public static final DeferredBlock<Block> MACHINE_FRAME_2;
	public static final DeferredBlock<Block> STEEL_TABLE;
	public static final DeferredBlock<Block> STEEL_STAIRCASE;
	public static final DeferredBlock<Block> WHITE_STAIRCASE;
	public static final DeferredBlock<Block> DARK_STAIRCASE;
	public static final DeferredBlock<Block> STEEL_CHAIR;
	public static final DeferredBlock<Block> WOOD_CHAIR;
	public static final DeferredBlock<Block> OFICE_BLACK_CHAIR;
	public static final DeferredBlock<Block> OFICE_WHITE_CHAIR;
	public static final DeferredBlock<Block> BAR_CHAIR;
	public static final DeferredBlock<Block> KOSTILNIBLOK;
	public static final DeferredBlock<Block> DEBUG_GRAV_GEN;
	public static final DeferredBlock<Block> NUCLEAR_WARHEAD;
	public static final DeferredBlock<Block> DIRT;
	public static final DeferredBlock<Block> GRASS_LIGHT_BLOCK;
	public static final DeferredBlock<Block> LOW_PLANET_GRASS;
	public static final DeferredBlock<Block> MED_PLANET_GRASS;
	public static final DeferredBlock<Block> PLANETARY_TREE_LOG;
	public static final DeferredBlock<Block> PLANETARY_TREE_FOLIAGE;
	public static final DeferredBlock<Block> UP_STEEL_STAIRCASE;
	public static final DeferredBlock<Block> UP_WHITE_STAIRCASE;
	public static final DeferredBlock<Block> UP_DARK_STAIRCASE;
	public static final DeferredBlock<Block> SHUTTLE_WALL;
	public static final DeferredBlock<Block> ARMORED_SHUTTLE_WALL;
	public static final DeferredBlock<Block> DIRECTED_BASE_WINDOW;
	public static final DeferredBlock<Block> COMPUTER;
	public static final DeferredBlock<Block> CLOSET_SECURE;
	public static final DeferredBlock<Block> UP_CLOSET_PLUG;
	public static final DeferredBlock<Block> CLOSET;
	public static final DeferredBlock<Block> FENCE_LINE;
	public static final DeferredBlock<Block> FENCE_G;
	public static final DeferredBlock<Block> FENCE_POINT;
	public static final DeferredBlock<Block> FENCE_P;
	public static final DeferredBlock<Block> DEBUG_13;
	public static final DeferredBlock<Block> EXTINGUISHER_CABINET;
	public static final DeferredBlock<Block> TITLE_STEEL_PAVEMENT_VERTICAL;
	public static final DeferredBlock<Block> COMMUNICATION_SERVERS;
	public static final DeferredBlock<Block> WOOD_TABLE;
	public static final DeferredBlock<Block> GRAV_GEN_PLUG_BLOCK;
	public static final DeferredBlock<Block> COMMUNICATION_CONSOLE;
	public static final DeferredBlock<Block> TECH_AIRLOCK_D_1;
	public static final DeferredBlock<Block> GAS_PRODUCER_O_2;
	public static final DeferredBlock<Block> VENDING_AUT_1;
	public static final DeferredBlock<Block> VENDING_KOSTIL;
	public static final DeferredBlock<Block> DIRECTED_ARMORED_WINDOW;
	public static final DeferredBlock<Block> SHUTTERS;
	public static final DeferredBlock<Block> BUTTON;
	public static final DeferredBlock<Block> MICROWAWE;
	public static final DeferredBlock<Block> TITLE_ARCADEBLUE;
	public static final DeferredBlock<Block> TITLEARCADEBLUE_2;
	public static final DeferredBlock<Block> TITLE_ARCADERED;
	public static final DeferredBlock<Block> TITLE_BAR;
	public static final DeferredBlock<Block> TITLE_BLUE_CIRCUIT;
	public static final DeferredBlock<Block> TITLE_BLUE;
	public static final DeferredBlock<Block> TITLE_BOXING;
	public static final DeferredBlock<Block> TITLE_CAFETERIA;
	public static final DeferredBlock<Block> TITLE_CARPETCLOWN;
	public static final DeferredBlock<Block> TITLE_CARPETOFFICE;
	public static final DeferredBlock<Block> TITLE_CHECKERDARK;
	public static final DeferredBlock<Block> TITLE_CLOWN;
	public static final DeferredBlock<Block> TITLE_DARKTEST;
	public static final DeferredBlock<Block> TITLEEIGHTIES;
	public static final DeferredBlock<Block> TITLE_ELEVATORSHAFT;
	public static final DeferredBlock<Block> TITLE_EXOBORG;
	public static final DeferredBlock<Block> TITLE_FREEZER;
	public static final DeferredBlock<Block> TITLE_GOLD;
	public static final DeferredBlock<Block> TITLE_GRATINGMAINT;
	public static final DeferredBlock<Block> TITLE_GREENCIRCUIT;
	public static final DeferredBlock<Block> TITLE_GYM;
	public static final DeferredBlock<Block> TITLE_HULLREINFORCED;
	public static final DeferredBlock<Block> TITLE_HULL;
	public static final DeferredBlock<Block> TITLE_HYDRO;
	public static final DeferredBlock<Block> TITLE_KITCHEN;
	public static final DeferredBlock<Block> TITLE_LAUNDRY;
	public static final DeferredBlock<Block> TITLE_LIME;
	public static final DeferredBlock<Block> TITLE_LINO;
	public static final DeferredBlock<Block> TITLE_MEAT;
	public static final DeferredBlock<Block> TITLE_METALDIAMOND;
	public static final DeferredBlock<Block> TITLE_MIME;
	public static final DeferredBlock<Block> TITLE_MININGFLOORDARK;
	public static final DeferredBlock<Block> TITLE_MININGFLOORLIGHT;
	public static final DeferredBlock<Block> TITLE_MININGFLOOR;
	public static final DeferredBlock<Block> TITLE_MONO;
	public static final DeferredBlock<Block> TITLE_REDCIRCUIT;
	public static final DeferredBlock<Block> TITLE_REINFORCED;
	public static final DeferredBlock<Block> TITLE_ROCKVAULT;
	public static final DeferredBlock<Block> TITLE_SHOWROOM;
	public static final DeferredBlock<Block> TITLE_SHUTTLEBLACK;
	public static final DeferredBlock<Block> TITLE_SHUTTLEBLUE;
	public static final DeferredBlock<Block> TITLE_SHUTTLEGREY;
	public static final DeferredBlock<Block> TITLE_SHUTTLEORANGE;
	public static final DeferredBlock<Block> TITLE_SHUTTLEPURPLE;
	public static final DeferredBlock<Block> TITLE_SHUTTLERED;
	public static final DeferredBlock<Block> TITLE_SHUTTLEWHITE;
	public static final DeferredBlock<Block> TITLE_SILVER;
	public static final DeferredBlock<Block> TITLE_STEELDAMAGED;
	public static final DeferredBlock<Block> TITLE_STEELDIRTY;
	public static final DeferredBlock<Block> TITLE_STEELMAINT;
	public static final DeferredBlock<Block> TITLE_SUPERREINFORCED;
	public static final DeferredBlock<Block> TITLE_TECHMAINTDARK;
	public static final DeferredBlock<Block> TITLE_TECHMAINT;
	public static final DeferredBlock<Block> TITLE_WOODBROKEN;
	public static final DeferredBlock<Block> TITLE_WOODLARGE;
	public static final DeferredBlock<Block> TITLE_WOOD;
	public static final DeferredBlock<Block> TITLE_WOODTILE;
	public static final DeferredBlock<Block> ATMOSPHERICS_AIRLOCK_D_1;
	public static final DeferredBlock<Block> CARGO_AIRLOCK_D_1;
	public static final DeferredBlock<Block> CENT_COM_AIRLOCK_D_1;
	public static final DeferredBlock<Block> CHEMISTRY_AIRLOCK_D_1;
	public static final DeferredBlock<Block> COMMAND_AIRLOCK_D_1;
	public static final DeferredBlock<Block> ENGINEERING_AIRLOCK_D_1;
	public static final DeferredBlock<Block> HYDROPONICS_AIRLOCK_D_1;
	public static final DeferredBlock<Block> MEDICAL_AIRLOCK_D_1;
	public static final DeferredBlock<Block> SALVAGE_AIRLOCK_D_1;
	public static final DeferredBlock<Block> SCIENCE_AIRLOCK_D_1;
	public static final DeferredBlock<Block> SECURITY_AIRLOCK_D_1;
	public static final DeferredBlock<Block> SYNDICATE_AIRLOCK_D_1;
	public static final DeferredBlock<Block> VIROLOGY_AIRLOCK_D_1;
	public static final DeferredBlock<Block> CLOSET_EMERG;
	public static final DeferredBlock<Block> CLOSET_FIRE;
	public static final DeferredBlock<Block> CLOSET_BLACK;
	public static final DeferredBlock<Block> CLOSET_BLUE;
	public static final DeferredBlock<Block> CLOSET_GRAY;
	public static final DeferredBlock<Block> CLOSET_GREEN;
	public static final DeferredBlock<Block> CLOSET_MIXED;
	public static final DeferredBlock<Block> CLOSET_N_2;
	public static final DeferredBlock<Block> CLOSET_ORANGE;
	public static final DeferredBlock<Block> CLOSET_PINK;
	public static final DeferredBlock<Block> GLASS_TABLE;
	public static final DeferredBlock<Block> GLASS_AIRLOCK_D_1;
	public static final DeferredBlock<Block> BASE_GLASS_AIRLOCK_D_1;
	static {
		ROD_FLOOR = register("rod_floor", RodFloorBlock::new);
		SHEATHING = register("sheathing", SheathingBlock::new);
		TITLE_STEEL = register("title_steel", TitleSteelBlock::new);
		STEEL_WALL = register("steel_wall", SteelWallBlock::new);
		WALL_CARCASE = register("wall_carcase", WallCarcaseBlock::new);
		UPER_SHEATHING = register("uper_sheathing", UperSheathingBlock::new);
		ROD_UP_FLOOR = register("rod_up_floor", RodUpFloorBlock::new);
		BASE_AIRLOCK_D_1 = register("base_airlock_d_1", BaseAirlockD1Block::new);
		UP_TITLE = register("up_title", UpTitleBlock::new);
		CONSOLE_OF_ID = register("console_of_id", ConsoleOfIDBlock::new);
		BASE_WINDOW = register("base_window", BaseWindowBlock::new);
		PORTABLE_SHEATER = register("portable_sheater", PortableSheaterBlock::new);
		PLASTEEL_WALL = register("plasteel_wall", PlasteelWallBlock::new);
		PLASTEEL_WALL_CARCASE = register("plasteel_wall_carcase", PlasteelWallCarcaseBlock::new);
		TITLE_DARK = register("title_dark", TitleDarkBlock::new);
		APC = register("apc", APCBlock::new);
		PODSTATION = register("podstation", PodstationBlock::new);
		DEBU_GGENERATOR = register("debu_ggenerator", DEBUGgeneratorBlock::new);
		LAMP = register("lamp", LampBlock::new);
		AIRLOCK_UP_PLUG = register("airlock_up_plug", AirlockUpPlugBlock::new);
		AIRLOCK_UP_PLUG_OPEN = register("airlock_up_plug_open", AirlockUpPlugOPENBlock::new);
		TITLE_STEEL_DIAGONAL_MINI = register("title_steel_diagonal_mini", TitleSteelDiagonalMiniBlock::new);
		TITLE_STEEL_DIAGONAL = register("title_steel_diagonal", TitleSteelDiagonalBlock::new);
		UP_TITLE_STEEL = register("up_title_steel", UpTitleSteelBlock::new);
		UP_TITLE_DARK = register("up_title_dark", UpTitleDarkBlock::new);
		TITLE_STEEL_MINI = register("title_steel_mini", TitleSteelMiniBlock::new);
		TITLE_STEEL_MONO = register("title_steel_mono", TitleSteelMonoBlock::new);
		TITLE_STEEL_OFFSET = register("title_steel_offset", TitleSteelOffsetBlock::new);
		TITLE_STEEL_PAVEMENT = register("title_steel_pavement", TitleSteelPavementBlock::new);
		TITLE_STEEL_HERRINGBONE = register("title_steel_herringbone", TitleSteelHerringboneBlock::new);
		TITLE_PLASTIC = register("title_plastic", TitlePlasticBlock::new);
		TITLE_DARK_DIAGONAL_MINI = register("title_dark_diagonal_mini", TitleDarkDiagonalMiniBlock::new);
		TITLE_DARK_DIAGONAL = register("title_dark_diagonal", TitleDarkDiagonalBlock::new);
		TITLE_DARK_MINI = register("title_dark_mini", TitleDarkMiniBlock::new);
		TITLE_DARK_MONO = register("title_dark_mono", TitleDarkMonoBlock::new);
		TITLE_DARK_OFFSET = register("title_dark_offset", TitleDarkOffsetBlock::new);
		TITLE_DARK_PAVEMENT = register("title_dark_pavement", TitleDarkPavementBlock::new);
		TITLE_DARK_PAVEMENT_VERTICAL = register("title_dark_pavement_vertical", TitleDarkPavementVerticalBlock::new);
		TITLE_DARK_HERRINGBONE = register("title_dark_herringbone", TitleDarkHerringboneBlock::new);
		TITLE_DARK_PLASTIC = register("title_dark_plastic", TitleDarkPlasticBlock::new);
		SMES = register("smes", SMESBlock::new);
		TECH_LAMP = register("tech_lamp", TechLampBlock::new);
		ARMORED_WINDOW = register("armored_window", ArmoredWindowBlock::new);
		DEBUG_LAMP = register("debug_lamp", DEBUGLampBlock::new);
		DEBUG_TECH_LAMP = register("debug_tech_lamp", DEBUGTechLampBlock::new);
		GRILLE = register("grille", GrilleBlock::new);
		BROKEN_GRILLE = register("broken_grille", BrokenGrilleBlock::new);
		ASTEROID_STONE_BASE = register("asteroid_stone_base", AsteroidStoneBaseBlock::new);
		ASTEROID_STONE_IRON = register("asteroid_stone_iron", AsteroidStoneIronBlock::new);
		ASTEROID_STONE_QUARTZ = register("asteroid_stone_quartz", AsteroidStoneQuartzBlock::new);
		ASTEROID_STONE_COAL = register("asteroid_stone_coal", AsteroidStoneCoalBlock::new);
		ASTEROID_STONE_GOLD = register("asteroid_stone_gold", AsteroidStoneGoldBlock::new);
		ASTEROID_STONE_PLASMA = register("asteroid_stone_plasma", AsteroidStonePlasmaBlock::new);
		ASTEROID_STONE_SILVER = register("asteroid_stone_silver", AsteroidStoneSilverBlock::new);
		ASTEROID_STONE_URAN = register("asteroid_stone_uran", AsteroidStoneUranBlock::new);
		ASTEROID_STONE_DIAMOND = register("asteroid_stone_diamond", AsteroidStoneDiamondBlock::new);
		CAVE_FLOOR_1 = register("cave_floor_1", CaveFloor1Block::new);
		CAVE_FLOOR_2 = register("cave_floor_2", CaveFloor2Block::new);
		CAVE_FLOOR_3 = register("cave_floor_3", CaveFloor3Block::new);
		CAVE_FLOOR_4 = register("cave_floor_4", CaveFloor4Block::new);
		CAVE_FLOOR_5 = register("cave_floor_5", CaveFloor5Block::new);
		CAVE_FLOOR_6 = register("cave_floor_6", CaveFloor6Block::new);
		CAVE_FLOOR_7 = register("cave_floor_7", CaveFloor7Block::new);
		GRAVITY_GENERATOR = register("gravity_generator", GravityGeneratorBlock::new);
		TITLE_WHITE = register("title_white", TitleWhiteBlock::new);
		TITLE_WHITE_DIAGONAL_MINI = register("title_white_diagonal_mini", TitleWhiteDiagonalMiniBlock::new);
		CATWALK_FLOOR = register("catwalk_floor", CatwalkFloorBlock::new);
		TITLE_WHITE_DIAGONAL = register("title_white_diagonal", TitleWhiteDiagonalBlock::new);
		TITLE_WHITE_HERRINGBONE = register("title_white_herringbone", TitleWhiteHerringboneBlock::new);
		TITLE_WHITE_MINI = register("title_white_mini", TitleWhiteMiniBlock::new);
		TITLE_WHITE_MONO = register("title_white_mono", TitleWhiteMonoBlock::new);
		TITLE_WHITE_OFFSET = register("title_white_offset", TitleWhiteOffsetBlock::new);
		TITLE_WHITE_PAVEMENT = register("title_white_pavement", TitleWhitePavementBlock::new);
		TITLE_WHITE_PAVEMENT_VERTICAL = register("title_white_pavement_vertical", TitleWhitePavementVerticalBlock::new);
		TITLE_WHITE_PLASTIC = register("title_white_plastic", TitleWhitePlasticBlock::new);
		C_4 = register("c_4", C4Block::new);
		MACHINE_FRAME = register("machine_frame", MachineFrameBlock::new);
		MACHINE_FRAME_2 = register("machine_frame_2", MachineFrame2Block::new);
		STEEL_TABLE = register("steel_table", SteelTableBlock::new);
		STEEL_STAIRCASE = register("steel_staircase", SteelStaircaseBlock::new);
		WHITE_STAIRCASE = register("white_staircase", WhiteStaircaseBlock::new);
		DARK_STAIRCASE = register("dark_staircase", DarkStaircaseBlock::new);
		STEEL_CHAIR = register("steel_chair", SteelChairBlock::new);
		WOOD_CHAIR = register("wood_chair", WoodChairBlock::new);
		OFICE_BLACK_CHAIR = register("ofice_black_chair", OficeBlackChairBlock::new);
		OFICE_WHITE_CHAIR = register("ofice_white_chair", OficeWhiteChairBlock::new);
		BAR_CHAIR = register("bar_chair", BarChairBlock::new);
		KOSTILNIBLOK = register("kostilniblok", KostilniblokBlock::new);
		DEBUG_GRAV_GEN = register("debug_grav_gen", DebugGravGenBlock::new);
		NUCLEAR_WARHEAD = register("nuclear_warhead", NuclearWarheadBlock::new);
		DIRT = register("dirt", DirtBlock::new);
		GRASS_LIGHT_BLOCK = register("grass_light_block", GrassLightBlockBlock::new);
		LOW_PLANET_GRASS = register("low_planet_grass", LowPlanetGrassBlock::new);
		MED_PLANET_GRASS = register("med_planet_grass", MedPlanetGrassBlock::new);
		PLANETARY_TREE_LOG = register("planetary_tree_log", PlanetaryTreeLogBlock::new);
		PLANETARY_TREE_FOLIAGE = register("planetary_tree_foliage", PlanetaryTreeFoliageBlock::new);
		UP_STEEL_STAIRCASE = register("up_steel_staircase", UpSteelStaircaseBlock::new);
		UP_WHITE_STAIRCASE = register("up_white_staircase", UpWhiteStaircaseBlock::new);
		UP_DARK_STAIRCASE = register("up_dark_staircase", UpDarkStaircaseBlock::new);
		SHUTTLE_WALL = register("shuttle_wall", ShuttleWallBlock::new);
		ARMORED_SHUTTLE_WALL = register("armored_shuttle_wall", ArmoredShuttleWallBlock::new);
		DIRECTED_BASE_WINDOW = register("directed_base_window", DirectedBaseWindowBlock::new);
		COMPUTER = register("computer", ComputerBlock::new);
		CLOSET_SECURE = register("closet_secure", ClosetSecureBlock::new);
		UP_CLOSET_PLUG = register("up_closet_plug", UpClosetPLUGBlock::new);
		CLOSET = register("closet", ClosetBlock::new);
		FENCE_LINE = register("fence_line", FenceLineBlock::new);
		FENCE_G = register("fence_g", FenceGBlock::new);
		FENCE_POINT = register("fence_point", FencePointBlock::new);
		FENCE_P = register("fence_p", FencePBlock::new);
		DEBUG_13 = register("debug_13", DEBUG13Block::new);
		EXTINGUISHER_CABINET = register("extinguisher_cabinet", ExtinguisherCabinetBlock::new);
		TITLE_STEEL_PAVEMENT_VERTICAL = register("title_steel_pavement_vertical", TitleSteelPavementVerticalBlock::new);
		COMMUNICATION_SERVERS = register("communication_servers", CommunicationServersBlock::new);
		WOOD_TABLE = register("wood_table", WoodTableBlock::new);
		GRAV_GEN_PLUG_BLOCK = register("grav_gen_plug_block", GravGenPlugBlockBlock::new);
		COMMUNICATION_CONSOLE = register("communication_console", CommunicationConsoleBlock::new);
		TECH_AIRLOCK_D_1 = register("tech_airlock_d_1", TechAirlockD1Block::new);
		GAS_PRODUCER_O_2 = register("gas_producer_o_2", GasProducerO2Block::new);
		VENDING_AUT_1 = register("vending_aut_1", VendingAut1Block::new);
		VENDING_KOSTIL = register("vending_kostil", VendingKOSTILBlock::new);
		DIRECTED_ARMORED_WINDOW = register("directed_armored_window", DirectedArmoredWindowBlock::new);
		SHUTTERS = register("shutters", ShuttersBlock::new);
		BUTTON = register("button", ButtonBlock::new);
		MICROWAWE = register("microwawe", MicrowaweBlock::new);
		TITLE_ARCADEBLUE = register("title_arcadeblue", TitleArcadeblueBlock::new);
		TITLEARCADEBLUE_2 = register("titlearcadeblue_2", Titlearcadeblue2Block::new);
		TITLE_ARCADERED = register("title_arcadered", TitleArcaderedBlock::new);
		TITLE_BAR = register("title_bar", TitleBarBlock::new);
		TITLE_BLUE_CIRCUIT = register("title_blue_circuit", TitleBlueCircuitBlock::new);
		TITLE_BLUE = register("title_blue", TitleBlueBlock::new);
		TITLE_BOXING = register("title_boxing", TitleBoxingBlock::new);
		TITLE_CAFETERIA = register("title_cafeteria", TitleCafeteriaBlock::new);
		TITLE_CARPETCLOWN = register("title_carpetclown", TitleCarpetclownBlock::new);
		TITLE_CARPETOFFICE = register("title_carpetoffice", TitleCarpetofficeBlock::new);
		TITLE_CHECKERDARK = register("title_checkerdark", TitleCheckerdarkBlock::new);
		TITLE_CLOWN = register("title_clown", TitleClownBlock::new);
		TITLE_DARKTEST = register("title_darktest", TitleDarktestBlock::new);
		TITLEEIGHTIES = register("titleeighties", TitleeightiesBlock::new);
		TITLE_ELEVATORSHAFT = register("title_elevatorshaft", TitleElevatorshaftBlock::new);
		TITLE_EXOBORG = register("title_exoborg", TitleExoborgBlock::new);
		TITLE_FREEZER = register("title_freezer", TitleFreezerBlock::new);
		TITLE_GOLD = register("title_gold", TitleGoldBlock::new);
		TITLE_GRATINGMAINT = register("title_gratingmaint", TitleGratingmaintBlock::new);
		TITLE_GREENCIRCUIT = register("title_greencircuit", TitleGreencircuitBlock::new);
		TITLE_GYM = register("title_gym", TitleGymBlock::new);
		TITLE_HULLREINFORCED = register("title_hullreinforced", TitleHullreinforcedBlock::new);
		TITLE_HULL = register("title_hull", TitleHullBlock::new);
		TITLE_HYDRO = register("title_hydro", TitleHydroBlock::new);
		TITLE_KITCHEN = register("title_kitchen", TitleKitchenBlock::new);
		TITLE_LAUNDRY = register("title_laundry", TitleLaundryBlock::new);
		TITLE_LIME = register("title_lime", TitleLimeBlock::new);
		TITLE_LINO = register("title_lino", TitleLinoBlock::new);
		TITLE_MEAT = register("title_meat", TitleMeatBlock::new);
		TITLE_METALDIAMOND = register("title_metaldiamond", TitleMetaldiamondBlock::new);
		TITLE_MIME = register("title_mime", TitleMimeBlock::new);
		TITLE_MININGFLOORDARK = register("title_miningfloordark", TitleMiningfloordarkBlock::new);
		TITLE_MININGFLOORLIGHT = register("title_miningfloorlight", TitleMiningfloorlightBlock::new);
		TITLE_MININGFLOOR = register("title_miningfloor", TitleMiningfloorBlock::new);
		TITLE_MONO = register("title_mono", TitleMonoBlock::new);
		TITLE_REDCIRCUIT = register("title_redcircuit", TitleRedcircuitBlock::new);
		TITLE_REINFORCED = register("title_reinforced", TitleReinforcedBlock::new);
		TITLE_ROCKVAULT = register("title_rockvault", TitleRockvaultBlock::new);
		TITLE_SHOWROOM = register("title_showroom", TitleShowroomBlock::new);
		TITLE_SHUTTLEBLACK = register("title_shuttleblack", TitleShuttleblackBlock::new);
		TITLE_SHUTTLEBLUE = register("title_shuttleblue", TitleShuttleblueBlock::new);
		TITLE_SHUTTLEGREY = register("title_shuttlegrey", TitleShuttlegreyBlock::new);
		TITLE_SHUTTLEORANGE = register("title_shuttleorange", TitleShuttleorangeBlock::new);
		TITLE_SHUTTLEPURPLE = register("title_shuttlepurple", TitleShuttlepurpleBlock::new);
		TITLE_SHUTTLERED = register("title_shuttlered", TitleShuttleredBlock::new);
		TITLE_SHUTTLEWHITE = register("title_shuttlewhite", TitleShuttlewhiteBlock::new);
		TITLE_SILVER = register("title_silver", TitleSilverBlock::new);
		TITLE_STEELDAMAGED = register("title_steeldamaged", TitleSteeldamagedBlock::new);
		TITLE_STEELDIRTY = register("title_steeldirty", TitleSteeldirtyBlock::new);
		TITLE_STEELMAINT = register("title_steelmaint", TitleSteelmaintBlock::new);
		TITLE_SUPERREINFORCED = register("title_superreinforced", TitleSuperreinforcedBlock::new);
		TITLE_TECHMAINTDARK = register("title_techmaintdark", TitleTechmaintdarkBlock::new);
		TITLE_TECHMAINT = register("title_techmaint", TitleTechmaintBlock::new);
		TITLE_WOODBROKEN = register("title_woodbroken", TitleWoodbrokenBlock::new);
		TITLE_WOODLARGE = register("title_woodlarge", TitleWoodlargeBlock::new);
		TITLE_WOOD = register("title_wood", TitleWoodBlock::new);
		TITLE_WOODTILE = register("title_woodtile", TitleWoodtileBlock::new);
		ATMOSPHERICS_AIRLOCK_D_1 = register("atmospherics_airlock_d_1", AtmosphericsAirlockD1Block::new);
		CARGO_AIRLOCK_D_1 = register("cargo_airlock_d_1", CargoAirlockD1Block::new);
		CENT_COM_AIRLOCK_D_1 = register("cent_com_airlock_d_1", CentComAirlockD1Block::new);
		CHEMISTRY_AIRLOCK_D_1 = register("chemistry_airlock_d_1", ChemistryAirlockD1Block::new);
		COMMAND_AIRLOCK_D_1 = register("command_airlock_d_1", CommandAirlockD1Block::new);
		ENGINEERING_AIRLOCK_D_1 = register("engineering_airlock_d_1", EngineeringAirlockD1Block::new);
		HYDROPONICS_AIRLOCK_D_1 = register("hydroponics_airlock_d_1", HydroponicsAirlockD1Block::new);
		MEDICAL_AIRLOCK_D_1 = register("medical_airlock_d_1", MedicalAirlockD1Block::new);
		SALVAGE_AIRLOCK_D_1 = register("salvage_airlock_d_1", SalvageAirlockD1Block::new);
		SCIENCE_AIRLOCK_D_1 = register("science_airlock_d_1", ScienceAirlockD1Block::new);
		SECURITY_AIRLOCK_D_1 = register("security_airlock_d_1", SecurityAirlockD1Block::new);
		SYNDICATE_AIRLOCK_D_1 = register("syndicate_airlock_d_1", SyndicateAirlockD1Block::new);
		VIROLOGY_AIRLOCK_D_1 = register("virology_airlock_d_1", VirologyAirlockD1Block::new);
		CLOSET_EMERG = register("closet_emerg", ClosetEmergBlock::new);
		CLOSET_FIRE = register("closet_fire", ClosetFireBlock::new);
		CLOSET_BLACK = register("closet_black", ClosetBlackBlock::new);
		CLOSET_BLUE = register("closet_blue", ClosetBlueBlock::new);
		CLOSET_GRAY = register("closet_gray", ClosetGrayBlock::new);
		CLOSET_GREEN = register("closet_green", ClosetGreenBlock::new);
		CLOSET_MIXED = register("closet_mixed", ClosetMixedBlock::new);
		CLOSET_N_2 = register("closet_n_2", ClosetN2Block::new);
		CLOSET_ORANGE = register("closet_orange", ClosetOrangeBlock::new);
		CLOSET_PINK = register("closet_pink", ClosetPinkBlock::new);
		GLASS_TABLE = register("glass_table", GlassTableBlock::new);
		GLASS_AIRLOCK_D_1 = register("glass_airlock_d_1", GlassAirlockD1Block::new);
		BASE_GLASS_AIRLOCK_D_1 = register("base_glass_airlock_d_1", BaseGlassAirlockD1Block::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.BlockTintSources event) {
			GrassLightBlockBlock.blockColorLoad(event);
			LowPlanetGrassBlock.blockColorLoad(event);
			MedPlanetGrassBlock.blockColorLoad(event);
			PlanetaryTreeFoliageBlock.blockColorLoad(event);
		}
	}
}