/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ssc.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.items.wrapper.SidedInvWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.Block;
import net.minecraft.core.registries.BuiltInRegistries;

import net.mcreator.ssc.block.entity.*;
import net.mcreator.ssc.Ssc14Mod;

@EventBusSubscriber
public class Ssc14ModBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTRY = DeferredRegister.create(BuiltInRegistries.BLOCK_ENTITY_TYPE, Ssc14Mod.MODID);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SheathingBlockEntity>> SHEATHING = register("sheathing", Ssc14ModBlocks.SHEATHING, SheathingBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<BaseAirlockD1BlockEntity>> BASE_AIRLOCK_D_1 = register("base_airlock_d_1", Ssc14ModBlocks.BASE_AIRLOCK_D_1, BaseAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ConsoleOfIDBlockEntity>> CONSOLE_OF_ID = register("console_of_id", Ssc14ModBlocks.CONSOLE_OF_ID, ConsoleOfIDBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PortableSheaterBlockEntity>> PORTABLE_SHEATER = register("portable_sheater", Ssc14ModBlocks.PORTABLE_SHEATER, PortableSheaterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<APCBlockEntity>> APC = register("apc", Ssc14ModBlocks.APC, APCBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PodstationBlockEntity>> PODSTATION = register("podstation", Ssc14ModBlocks.PODSTATION, PodstationBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DEBUGgeneratorBlockEntity>> DEBU_GGENERATOR = register("debu_ggenerator", Ssc14ModBlocks.DEBU_GGENERATOR, DEBUGgeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<LampBlockEntity>> LAMP = register("lamp", Ssc14ModBlocks.LAMP, LampBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AirlockUpPlugBlockEntity>> AIRLOCK_UP_PLUG = register("airlock_up_plug", Ssc14ModBlocks.AIRLOCK_UP_PLUG, AirlockUpPlugBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AirlockUpPlugOPENBlockEntity>> AIRLOCK_UP_PLUG_OPEN = register("airlock_up_plug_open", Ssc14ModBlocks.AIRLOCK_UP_PLUG_OPEN, AirlockUpPlugOPENBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SMESBlockEntity>> SMES = register("smes", Ssc14ModBlocks.SMES, SMESBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GravityGeneratorBlockEntity>> GRAVITY_GENERATOR = register("gravity_generator", Ssc14ModBlocks.GRAVITY_GENERATOR, GravityGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<C4BlockEntity>> C_4 = register("c_4", Ssc14ModBlocks.C_4, C4BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MachineFrame2BlockEntity>> MACHINE_FRAME_2 = register("machine_frame_2", Ssc14ModBlocks.MACHINE_FRAME_2, MachineFrame2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<KostilniblokBlockEntity>> KOSTILNIBLOK = register("kostilniblok", Ssc14ModBlocks.KOSTILNIBLOK, KostilniblokBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DebugGravGenBlockEntity>> DEBUG_GRAV_GEN = register("debug_grav_gen", Ssc14ModBlocks.DEBUG_GRAV_GEN, DebugGravGenBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<NuclearWarheadBlockEntity>> NUCLEAR_WARHEAD = register("nuclear_warhead", Ssc14ModBlocks.NUCLEAR_WARHEAD, NuclearWarheadBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetSecureBlockEntity>> CLOSET_SECURE = register("closet_secure", Ssc14ModBlocks.CLOSET_SECURE, ClosetSecureBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetBlockEntity>> CLOSET = register("closet", Ssc14ModBlocks.CLOSET, ClosetBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CommunicationServersBlockEntity>> COMMUNICATION_SERVERS = register("communication_servers", Ssc14ModBlocks.COMMUNICATION_SERVERS, CommunicationServersBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CommunicationConsoleBlockEntity>> COMMUNICATION_CONSOLE = register("communication_console", Ssc14ModBlocks.COMMUNICATION_CONSOLE, CommunicationConsoleBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TechAirlockD1BlockEntity>> TECH_AIRLOCK_D_1 = register("tech_airlock_d_1", Ssc14ModBlocks.TECH_AIRLOCK_D_1, TechAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<VendingAut1BlockEntity>> VENDING_AUT_1 = register("vending_aut_1", Ssc14ModBlocks.VENDING_AUT_1, VendingAut1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ShuttersBlockEntity>> SHUTTERS = register("shutters", Ssc14ModBlocks.SHUTTERS, ShuttersBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ButtonBlockEntity>> BUTTON = register("button", Ssc14ModBlocks.BUTTON, ButtonBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MicrowaweBlockEntity>> MICROWAWE = register("microwawe", Ssc14ModBlocks.MICROWAWE, MicrowaweBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleCarpetclownBlockEntity>> TITLE_CARPETCLOWN = register("title_carpetclown", Ssc14ModBlocks.TITLE_CARPETCLOWN, TitleCarpetclownBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleCarpetofficeBlockEntity>> TITLE_CARPETOFFICE = register("title_carpetoffice", Ssc14ModBlocks.TITLE_CARPETOFFICE, TitleCarpetofficeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleCheckerdarkBlockEntity>> TITLE_CHECKERDARK = register("title_checkerdark", Ssc14ModBlocks.TITLE_CHECKERDARK, TitleCheckerdarkBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleClownBlockEntity>> TITLE_CLOWN = register("title_clown", Ssc14ModBlocks.TITLE_CLOWN, TitleClownBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleDarktestBlockEntity>> TITLE_DARKTEST = register("title_darktest", Ssc14ModBlocks.TITLE_DARKTEST, TitleDarktestBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleeightiesBlockEntity>> TITLEEIGHTIES = register("titleeighties", Ssc14ModBlocks.TITLEEIGHTIES, TitleeightiesBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleElevatorshaftBlockEntity>> TITLE_ELEVATORSHAFT = register("title_elevatorshaft", Ssc14ModBlocks.TITLE_ELEVATORSHAFT, TitleElevatorshaftBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleExoborgBlockEntity>> TITLE_EXOBORG = register("title_exoborg", Ssc14ModBlocks.TITLE_EXOBORG, TitleExoborgBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleFreezerBlockEntity>> TITLE_FREEZER = register("title_freezer", Ssc14ModBlocks.TITLE_FREEZER, TitleFreezerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleGoldBlockEntity>> TITLE_GOLD = register("title_gold", Ssc14ModBlocks.TITLE_GOLD, TitleGoldBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleGratingmaintBlockEntity>> TITLE_GRATINGMAINT = register("title_gratingmaint", Ssc14ModBlocks.TITLE_GRATINGMAINT, TitleGratingmaintBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleGreencircuitBlockEntity>> TITLE_GREENCIRCUIT = register("title_greencircuit", Ssc14ModBlocks.TITLE_GREENCIRCUIT, TitleGreencircuitBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleGymBlockEntity>> TITLE_GYM = register("title_gym", Ssc14ModBlocks.TITLE_GYM, TitleGymBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleHullreinforcedBlockEntity>> TITLE_HULLREINFORCED = register("title_hullreinforced", Ssc14ModBlocks.TITLE_HULLREINFORCED, TitleHullreinforcedBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleHullBlockEntity>> TITLE_HULL = register("title_hull", Ssc14ModBlocks.TITLE_HULL, TitleHullBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleHydroBlockEntity>> TITLE_HYDRO = register("title_hydro", Ssc14ModBlocks.TITLE_HYDRO, TitleHydroBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleKitchenBlockEntity>> TITLE_KITCHEN = register("title_kitchen", Ssc14ModBlocks.TITLE_KITCHEN, TitleKitchenBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleLaundryBlockEntity>> TITLE_LAUNDRY = register("title_laundry", Ssc14ModBlocks.TITLE_LAUNDRY, TitleLaundryBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleLimeBlockEntity>> TITLE_LIME = register("title_lime", Ssc14ModBlocks.TITLE_LIME, TitleLimeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleLinoBlockEntity>> TITLE_LINO = register("title_lino", Ssc14ModBlocks.TITLE_LINO, TitleLinoBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMeatBlockEntity>> TITLE_MEAT = register("title_meat", Ssc14ModBlocks.TITLE_MEAT, TitleMeatBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMetaldiamondBlockEntity>> TITLE_METALDIAMOND = register("title_metaldiamond", Ssc14ModBlocks.TITLE_METALDIAMOND, TitleMetaldiamondBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMimeBlockEntity>> TITLE_MIME = register("title_mime", Ssc14ModBlocks.TITLE_MIME, TitleMimeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMiningfloordarkBlockEntity>> TITLE_MININGFLOORDARK = register("title_miningfloordark", Ssc14ModBlocks.TITLE_MININGFLOORDARK, TitleMiningfloordarkBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMiningfloorlightBlockEntity>> TITLE_MININGFLOORLIGHT = register("title_miningfloorlight", Ssc14ModBlocks.TITLE_MININGFLOORLIGHT, TitleMiningfloorlightBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMiningfloorBlockEntity>> TITLE_MININGFLOOR = register("title_miningfloor", Ssc14ModBlocks.TITLE_MININGFLOOR, TitleMiningfloorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleMonoBlockEntity>> TITLE_MONO = register("title_mono", Ssc14ModBlocks.TITLE_MONO, TitleMonoBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleRedcircuitBlockEntity>> TITLE_REDCIRCUIT = register("title_redcircuit", Ssc14ModBlocks.TITLE_REDCIRCUIT, TitleRedcircuitBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleReinforcedBlockEntity>> TITLE_REINFORCED = register("title_reinforced", Ssc14ModBlocks.TITLE_REINFORCED, TitleReinforcedBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleRockvaultBlockEntity>> TITLE_ROCKVAULT = register("title_rockvault", Ssc14ModBlocks.TITLE_ROCKVAULT, TitleRockvaultBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShowroomBlockEntity>> TITLE_SHOWROOM = register("title_showroom", Ssc14ModBlocks.TITLE_SHOWROOM, TitleShowroomBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttleblackBlockEntity>> TITLE_SHUTTLEBLACK = register("title_shuttleblack", Ssc14ModBlocks.TITLE_SHUTTLEBLACK, TitleShuttleblackBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttleblueBlockEntity>> TITLE_SHUTTLEBLUE = register("title_shuttleblue", Ssc14ModBlocks.TITLE_SHUTTLEBLUE, TitleShuttleblueBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttlegreyBlockEntity>> TITLE_SHUTTLEGREY = register("title_shuttlegrey", Ssc14ModBlocks.TITLE_SHUTTLEGREY, TitleShuttlegreyBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttleorangeBlockEntity>> TITLE_SHUTTLEORANGE = register("title_shuttleorange", Ssc14ModBlocks.TITLE_SHUTTLEORANGE, TitleShuttleorangeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttlepurpleBlockEntity>> TITLE_SHUTTLEPURPLE = register("title_shuttlepurple", Ssc14ModBlocks.TITLE_SHUTTLEPURPLE, TitleShuttlepurpleBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttleredBlockEntity>> TITLE_SHUTTLERED = register("title_shuttlered", Ssc14ModBlocks.TITLE_SHUTTLERED, TitleShuttleredBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleShuttlewhiteBlockEntity>> TITLE_SHUTTLEWHITE = register("title_shuttlewhite", Ssc14ModBlocks.TITLE_SHUTTLEWHITE, TitleShuttlewhiteBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleSilverBlockEntity>> TITLE_SILVER = register("title_silver", Ssc14ModBlocks.TITLE_SILVER, TitleSilverBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleSteeldamagedBlockEntity>> TITLE_STEELDAMAGED = register("title_steeldamaged", Ssc14ModBlocks.TITLE_STEELDAMAGED, TitleSteeldamagedBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleSteeldirtyBlockEntity>> TITLE_STEELDIRTY = register("title_steeldirty", Ssc14ModBlocks.TITLE_STEELDIRTY, TitleSteeldirtyBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleSteelmaintBlockEntity>> TITLE_STEELMAINT = register("title_steelmaint", Ssc14ModBlocks.TITLE_STEELMAINT, TitleSteelmaintBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleSuperreinforcedBlockEntity>> TITLE_SUPERREINFORCED = register("title_superreinforced", Ssc14ModBlocks.TITLE_SUPERREINFORCED, TitleSuperreinforcedBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleTechmaintdarkBlockEntity>> TITLE_TECHMAINTDARK = register("title_techmaintdark", Ssc14ModBlocks.TITLE_TECHMAINTDARK, TitleTechmaintdarkBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleTechmaintBlockEntity>> TITLE_TECHMAINT = register("title_techmaint", Ssc14ModBlocks.TITLE_TECHMAINT, TitleTechmaintBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleWoodbrokenBlockEntity>> TITLE_WOODBROKEN = register("title_woodbroken", Ssc14ModBlocks.TITLE_WOODBROKEN, TitleWoodbrokenBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleWoodlargeBlockEntity>> TITLE_WOODLARGE = register("title_woodlarge", Ssc14ModBlocks.TITLE_WOODLARGE, TitleWoodlargeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleWoodBlockEntity>> TITLE_WOOD = register("title_wood", Ssc14ModBlocks.TITLE_WOOD, TitleWoodBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TitleWoodtileBlockEntity>> TITLE_WOODTILE = register("title_woodtile", Ssc14ModBlocks.TITLE_WOODTILE, TitleWoodtileBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AtmosphericsAirlockD1BlockEntity>> ATMOSPHERICS_AIRLOCK_D_1 = register("atmospherics_airlock_d_1", Ssc14ModBlocks.ATMOSPHERICS_AIRLOCK_D_1,
			AtmosphericsAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CargoAirlockD1BlockEntity>> CARGO_AIRLOCK_D_1 = register("cargo_airlock_d_1", Ssc14ModBlocks.CARGO_AIRLOCK_D_1, CargoAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CentComAirlockD1BlockEntity>> CENT_COM_AIRLOCK_D_1 = register("cent_com_airlock_d_1", Ssc14ModBlocks.CENT_COM_AIRLOCK_D_1, CentComAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ChemistryAirlockD1BlockEntity>> CHEMISTRY_AIRLOCK_D_1 = register("chemistry_airlock_d_1", Ssc14ModBlocks.CHEMISTRY_AIRLOCK_D_1, ChemistryAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CommandAirlockD1BlockEntity>> COMMAND_AIRLOCK_D_1 = register("command_airlock_d_1", Ssc14ModBlocks.COMMAND_AIRLOCK_D_1, CommandAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<EngineeringAirlockD1BlockEntity>> ENGINEERING_AIRLOCK_D_1 = register("engineering_airlock_d_1", Ssc14ModBlocks.ENGINEERING_AIRLOCK_D_1, EngineeringAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<HydroponicsAirlockD1BlockEntity>> HYDROPONICS_AIRLOCK_D_1 = register("hydroponics_airlock_d_1", Ssc14ModBlocks.HYDROPONICS_AIRLOCK_D_1, HydroponicsAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MedicalAirlockD1BlockEntity>> MEDICAL_AIRLOCK_D_1 = register("medical_airlock_d_1", Ssc14ModBlocks.MEDICAL_AIRLOCK_D_1, MedicalAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SalvageAirlockD1BlockEntity>> SALVAGE_AIRLOCK_D_1 = register("salvage_airlock_d_1", Ssc14ModBlocks.SALVAGE_AIRLOCK_D_1, SalvageAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ScienceAirlockD1BlockEntity>> SCIENCE_AIRLOCK_D_1 = register("science_airlock_d_1", Ssc14ModBlocks.SCIENCE_AIRLOCK_D_1, ScienceAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SecurityAirlockD1BlockEntity>> SECURITY_AIRLOCK_D_1 = register("security_airlock_d_1", Ssc14ModBlocks.SECURITY_AIRLOCK_D_1, SecurityAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SyndicateAirlockD1BlockEntity>> SYNDICATE_AIRLOCK_D_1 = register("syndicate_airlock_d_1", Ssc14ModBlocks.SYNDICATE_AIRLOCK_D_1, SyndicateAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<VirologyAirlockD1BlockEntity>> VIROLOGY_AIRLOCK_D_1 = register("virology_airlock_d_1", Ssc14ModBlocks.VIROLOGY_AIRLOCK_D_1, VirologyAirlockD1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetEmergBlockEntity>> CLOSET_EMERG = register("closet_emerg", Ssc14ModBlocks.CLOSET_EMERG, ClosetEmergBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetFireBlockEntity>> CLOSET_FIRE = register("closet_fire", Ssc14ModBlocks.CLOSET_FIRE, ClosetFireBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetBlackBlockEntity>> CLOSET_BLACK = register("closet_black", Ssc14ModBlocks.CLOSET_BLACK, ClosetBlackBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetBlueBlockEntity>> CLOSET_BLUE = register("closet_blue", Ssc14ModBlocks.CLOSET_BLUE, ClosetBlueBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetGrayBlockEntity>> CLOSET_GRAY = register("closet_gray", Ssc14ModBlocks.CLOSET_GRAY, ClosetGrayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetGreenBlockEntity>> CLOSET_GREEN = register("closet_green", Ssc14ModBlocks.CLOSET_GREEN, ClosetGreenBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetMixedBlockEntity>> CLOSET_MIXED = register("closet_mixed", Ssc14ModBlocks.CLOSET_MIXED, ClosetMixedBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetN2BlockEntity>> CLOSET_N_2 = register("closet_n_2", Ssc14ModBlocks.CLOSET_N_2, ClosetN2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetOrangeBlockEntity>> CLOSET_ORANGE = register("closet_orange", Ssc14ModBlocks.CLOSET_ORANGE, ClosetOrangeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ClosetPinkBlockEntity>> CLOSET_PINK = register("closet_pink", Ssc14ModBlocks.CLOSET_PINK, ClosetPinkBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GlassAirlockD1BlockEntity>> GLASS_AIRLOCK_D_1 = register("glass_airlock_d_1", Ssc14ModBlocks.GLASS_AIRLOCK_D_1, GlassAirlockD1BlockEntity::new);

	// Start of user code block custom block entities
	// End of user code block custom block entities
	private static <T extends BlockEntity> DeferredHolder<BlockEntityType<?>, BlockEntityType<T>> register(String registryname, DeferredHolder<Block, Block> block, BlockEntityType.BlockEntitySupplier<T> supplier) {
		return REGISTRY.register(registryname, () -> new BlockEntityType(supplier, block.get()));
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SHEATHING.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BASE_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CONSOLE_OF_ID.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PORTABLE_SHEATER.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, APC.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PODSTATION.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DEBU_GGENERATOR.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, LAMP.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, AIRLOCK_UP_PLUG.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, AIRLOCK_UP_PLUG_OPEN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SMES.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, GRAVITY_GENERATOR.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, C_4.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MACHINE_FRAME_2.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, KOSTILNIBLOK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DEBUG_GRAV_GEN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, NUCLEAR_WARHEAD.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_SECURE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMMUNICATION_SERVERS.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMMUNICATION_CONSOLE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TECH_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, VENDING_AUT_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SHUTTERS.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BUTTON.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MICROWAWE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_CARPETCLOWN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_CARPETOFFICE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_CHECKERDARK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_CLOWN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_DARKTEST.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLEEIGHTIES.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_ELEVATORSHAFT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_EXOBORG.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_FREEZER.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_GOLD.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_GRATINGMAINT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_GREENCIRCUIT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_GYM.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_HULLREINFORCED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_HULL.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_HYDRO.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_KITCHEN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_LAUNDRY.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_LIME.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_LINO.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MEAT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_METALDIAMOND.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MIME.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MININGFLOORDARK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MININGFLOORLIGHT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MININGFLOOR.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_MONO.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_REDCIRCUIT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_REINFORCED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_ROCKVAULT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHOWROOM.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEBLACK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEBLUE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEGREY.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEORANGE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEPURPLE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLERED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SHUTTLEWHITE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SILVER.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_STEELDAMAGED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_STEELDIRTY.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_STEELMAINT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_SUPERREINFORCED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_TECHMAINTDARK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_TECHMAINT.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_WOODBROKEN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_WOODLARGE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_WOOD.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TITLE_WOODTILE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ATMOSPHERICS_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CARGO_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CENT_COM_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CHEMISTRY_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMMAND_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ENGINEERING_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, HYDROPONICS_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MEDICAL_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SALVAGE_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SCIENCE_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SECURITY_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SYNDICATE_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, VIROLOGY_AIRLOCK_D_1.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_EMERG.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_FIRE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_BLACK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_BLUE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_GRAY.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_GREEN.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_MIXED.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_N_2.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_ORANGE.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CLOSET_PINK.get(), SidedInvWrapper::new);
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, GLASS_AIRLOCK_D_1.get(), SidedInvWrapper::new);
	}
}