/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ssc.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.ssc.item.inventory.PDApassangerInventoryCapability;
import net.mcreator.ssc.item.inventory.AccessConfigInventoryCapability;
import net.mcreator.ssc.item.*;
import net.mcreator.ssc.block.FencePointBlock;
import net.mcreator.ssc.block.FencePBlock;
import net.mcreator.ssc.block.FenceLineBlock;
import net.mcreator.ssc.block.FenceGBlock;
import net.mcreator.ssc.Ssc14Mod;

import java.util.function.Function;

@EventBusSubscriber
public class Ssc14ModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(Ssc14Mod.MODID);
	public static final DeferredItem<Item> ROD_FLOOR;
	public static final DeferredItem<Item> ROOD;
	public static final DeferredItem<Item> SHEATHING;
	public static final DeferredItem<Item> STEEL;
	public static final DeferredItem<Item> PLASTEEL;
	public static final DeferredItem<Item> LOW_VOLTAGE_CABLE;
	public static final DeferredItem<Item> MEDIUM_VOLTAGE_CABLE;
	public static final DeferredItem<Item> HIGH_VOLTAGE_CABLE;
	public static final DeferredItem<Item> CROWBAR;
	public static final DeferredItem<Item> TITLE_STEEL;
	public static final DeferredItem<Item> STEEL_WALL;
	public static final DeferredItem<Item> WALL_CARCASE;
	public static final DeferredItem<Item> WELDING;
	public static final DeferredItem<Item> ACTIVE_WELDER;
	public static final DeferredItem<Item> NIPPERS;
	public static final DeferredItem<Item> FIRE_AXE;
	public static final DeferredItem<Item> UPER_SHEATHING;
	public static final DeferredItem<Item> ROD_UP_FLOOR;
	public static final DeferredItem<Item> SCREWDRIVER;
	public static final DeferredItem<Item> SPANNER;
	public static final DeferredItem<Item> BASE_AIRLOCK_D_1;
	public static final DeferredItem<Item> UP_TITLE;
	public static final DeferredItem<Item> WALL_CARCASE_ENTIT_SPAWN_EGG;
	public static final DeferredItem<Item> ID_CARD_PASSANGER;
	public static final DeferredItem<Item> CONSOLE_OF_ID;
	public static final DeferredItem<Item> ID_CONSOLE_ENTITY_SPAWN_EGG;
	public static final DeferredItem<Item> GAS_ANALYSER;
	public static final DeferredItem<Item> BASE_WINDOW;
	public static final DeferredItem<Item> GLASS_SHARD;
	public static final DeferredItem<Item> GLASS;
	public static final DeferredItem<Item> ACCESS_CONFIG;
	public static final DeferredItem<Item> ID_CARD_CAPITAN;
	public static final DeferredItem<Item> ID_CARD_PNT;
	public static final DeferredItem<Item> ID_CARD_ADUTANT;
	public static final DeferredItem<Item> ID_CARD_AVD;
	public static final DeferredItem<Item> ID_CARD_OSH;
	public static final DeferredItem<Item> ID_CARD_MIME;
	public static final DeferredItem<Item> ID_CARD_CLOWN;
	public static final DeferredItem<Item> ID_CARD_HO_P;
	public static final DeferredItem<Item> ID_CARD_SERVICE_W;
	public static final DeferredItem<Item> ID_CARD_CLEANER;
	public static final DeferredItem<Item> ID_CARD_CHEF;
	public static final DeferredItem<Item> ID_CARD_BOTANIK;
	public static final DeferredItem<Item> ID_CARD_BARMEN;
	public static final DeferredItem<Item> ID_CARD_PRIEST;
	public static final DeferredItem<Item> ID_CARD_QM;
	public static final DeferredItem<Item> ID_CARD_UTILIZATOR;
	public static final DeferredItem<Item> ID_CARD_LOADER;
	public static final DeferredItem<Item> ID_CARD_REPORTER;
	public static final DeferredItem<Item> ID_CARD_BOXER;
	public static final DeferredItem<Item> ID_CARD_BIBLIOTEKAR;
	public static final DeferredItem<Item> ID_CARD_ZOOTECHNIK;
	public static final DeferredItem<Item> ID_CARD_CE;
	public static final DeferredItem<Item> ID_CARD_VE;
	public static final DeferredItem<Item> ID_CARD_ATMOS;
	public static final DeferredItem<Item> ID_CARD_ENGENEER;
	public static final DeferredItem<Item> ID_CARD_TECH_ASSISTENT;
	public static final DeferredItem<Item> ID_CARD_MUSICANT;
	public static final DeferredItem<Item> ID_CARD_HO_S;
	public static final DeferredItem<Item> ID_CARD_INSTRUCTOR_S;
	public static final DeferredItem<Item> ID_CARD_WARD;
	public static final DeferredItem<Item> ID_CARD_DETECTIVE;
	public static final DeferredItem<Item> ID_CARD_BRIG_MED;
	public static final DeferredItem<Item> ID_CARD_OFICER_S;
	public static final DeferredItem<Item> ID_CARD_KADET_S;
	public static final DeferredItem<Item> ID_CARD_CMO;
	public static final DeferredItem<Item> ID_CARD_VM;
	public static final DeferredItem<Item> ID_CARD_CHIMIC;
	public static final DeferredItem<Item> ID_CARD_PARAMED;
	public static final DeferredItem<Item> ID_CARD_MEDIC;
	public static final DeferredItem<Item> ID_CARD_PSIHOLOG;
	public static final DeferredItem<Item> ID_CARD_INTERN;
	public static final DeferredItem<Item> ID_CARD_RD;
	public static final DeferredItem<Item> ID_CARD_VS;
	public static final DeferredItem<Item> ID_CARD_SCIENTIST;
	public static final DeferredItem<Item> ID_CARD_SCI_ASSISTENT;
	public static final DeferredItem<Item> PORTABLE_SHEATER;
	public static final DeferredItem<Item> SILVER;
	public static final DeferredItem<Item> SSC_14_GOLD;
	public static final DeferredItem<Item> URAN;
	public static final DeferredItem<Item> PLASMA;
	public static final DeferredItem<Item> PLASTIC;
	public static final DeferredItem<Item> PLASTEEL_WALL;
	public static final DeferredItem<Item> PLASTEEL_WALL_CARCASE;
	public static final DeferredItem<Item> ENERGY_BAR;
	public static final DeferredItem<Item> ENERGY_BAR_TRASH;
	public static final DeferredItem<Item> ENERGY_BAR_2;
	public static final DeferredItem<Item> PLASSTEEL_WALL_CARCASE_ENTIT_SPAWN_EGG;
	public static final DeferredItem<Item> TITLE_DARK;
	public static final DeferredItem<Item> AIRLOCK_CONTROLLER;
	public static final DeferredItem<Item> APC;
	public static final DeferredItem<Item> PODSTATION;
	public static final DeferredItem<Item> DEBU_GGENERATOR;
	public static final DeferredItem<Item> LAMP;
	public static final DeferredItem<Item> TITLE_STEEL_DIAGONAL_MINI;
	public static final DeferredItem<Item> TITLE_STEEL_DIAGONAL;
	public static final DeferredItem<Item> UP_TITLE_STEEL;
	public static final DeferredItem<Item> UP_TITLE_DARK;
	public static final DeferredItem<Item> TITLE_STEEL_MINI;
	public static final DeferredItem<Item> TITLE_STEEL_MONO;
	public static final DeferredItem<Item> TITLE_STEEL_OFFSET;
	public static final DeferredItem<Item> TITLE_STEEL_PAVEMENT;
	public static final DeferredItem<Item> TITLE_STEEL_HERRINGBONE;
	public static final DeferredItem<Item> TITLE_PLASTIC;
	public static final DeferredItem<Item> TITLE_DARK_DIAGONAL_MINI;
	public static final DeferredItem<Item> TITLE_DARK_DIAGONAL;
	public static final DeferredItem<Item> TITLE_DARK_MINI;
	public static final DeferredItem<Item> TITLE_DARK_MONO;
	public static final DeferredItem<Item> TITLE_DARK_OFFSET;
	public static final DeferredItem<Item> TITLE_DARK_PAVEMENT;
	public static final DeferredItem<Item> TITLE_DARK_PAVEMENT_VERTICAL;
	public static final DeferredItem<Item> TITLE_DARK_HERRINGBONE;
	public static final DeferredItem<Item> TITLE_DARK_PLASTIC;
	public static final DeferredItem<Item> SMES;
	public static final DeferredItem<Item> TECH_LAMP;
	public static final DeferredItem<Item> LED_LIGHT_TUBE;
	public static final DeferredItem<Item> LIGHT_BULB;
	public static final DeferredItem<Item> LED_LIGHT_TUBE_BROKEN;
	public static final DeferredItem<Item> LIGHT_BULB_BROKEN;
	public static final DeferredItem<Item> ARMORED_WINDOW;
	public static final DeferredItem<Item> ARM_GLASS_SHARD;
	public static final DeferredItem<Item> ARM_GLASS;
	public static final DeferredItem<Item> DEBUG_LAMP;
	public static final DeferredItem<Item> DEBUG_TECH_LAMP;
	public static final DeferredItem<Item> GRILLE;
	public static final DeferredItem<Item> BROKEN_GRILLE;
	public static final DeferredItem<Item> ASTEROID_STONE_BASE;
	public static final DeferredItem<Item> RAW_IRON;
	public static final DeferredItem<Item> RAW_QUARTZ;
	public static final DeferredItem<Item> ASTEROID_STONE_IRON;
	public static final DeferredItem<Item> ASTEROID_STONE_QUARTZ;
	public static final DeferredItem<Item> ASTEROID_STONE_COAL;
	public static final DeferredItem<Item> ASTEROID_STONE_GOLD;
	public static final DeferredItem<Item> ASTEROID_STONE_PLASMA;
	public static final DeferredItem<Item> ASTEROID_STONE_SILVER;
	public static final DeferredItem<Item> ASTEROID_STONE_URAN;
	public static final DeferredItem<Item> ASTEROID_STONE_DIAMOND;
	public static final DeferredItem<Item> RAW_COAL;
	public static final DeferredItem<Item> RAW_GOLD;
	public static final DeferredItem<Item> RAW_PLASMA;
	public static final DeferredItem<Item> RAW_SILVER;
	public static final DeferredItem<Item> RAW_URAN;
	public static final DeferredItem<Item> RAW_DIAMOND;
	public static final DeferredItem<Item> CAVE_FLOOR_1;
	public static final DeferredItem<Item> GRAVITY_GENERATOR;
	public static final DeferredItem<Item> TITLE_WHITE;
	public static final DeferredItem<Item> TITLE_WHITE_DIAGONAL_MINI;
	public static final DeferredItem<Item> CATWALK_FLOOR;
	public static final DeferredItem<Item> TITLE_WHITE_DIAGONAL;
	public static final DeferredItem<Item> TITLE_WHITE_HERRINGBONE;
	public static final DeferredItem<Item> TITLE_WHITE_MINI;
	public static final DeferredItem<Item> TITLE_WHITE_MONO;
	public static final DeferredItem<Item> TITLE_WHITE_OFFSET;
	public static final DeferredItem<Item> TITLE_WHITE_PAVEMENT;
	public static final DeferredItem<Item> TITLE_WHITE_PAVEMENT_VERTICAL;
	public static final DeferredItem<Item> TITLE_WHITE_PLASTIC;
	public static final DeferredItem<Item> C_4;
	public static final DeferredItem<Item> MACHINE_FRAME;
	public static final DeferredItem<Item> MACHINE_FRAME_2;
	public static final DeferredItem<Item> CAPACITOR;
	public static final DeferredItem<Item> MATTER_BIN;
	public static final DeferredItem<Item> MICRO_MANIPULATOR;
	public static final DeferredItem<Item> SUBSTATION_BOARD;
	public static final DeferredItem<Item> SMES_BOARD;
	public static final DeferredItem<Item> APC_BOARD;
	public static final DeferredItem<Item> STEEL_TABLE;
	public static final DeferredItem<Item> LOW_BATTERIE;
	public static final DeferredItem<Item> STEEL_STAIRCASE;
	public static final DeferredItem<Item> WHITE_STAIRCASE;
	public static final DeferredItem<Item> DARK_STAIRCASE;
	public static final DeferredItem<Item> STEEL_CHAIR;
	public static final DeferredItem<Item> WOOD_CHAIR;
	public static final DeferredItem<Item> OFICE_BLACK_CHAIR;
	public static final DeferredItem<Item> OFICE_WHITE_CHAIR;
	public static final DeferredItem<Item> BAR_CHAIR;
	public static final DeferredItem<Item> KOSTILNIBLOK;
	public static final DeferredItem<Item> DEBUG_GRAV_GEN;
	public static final DeferredItem<Item> NUCLEAR_WARHEAD;
	public static final DeferredItem<Item> DIRT;
	public static final DeferredItem<Item> GRASS_LIGHT_BLOCK;
	public static final DeferredItem<Item> LOW_PLANET_GRASS;
	public static final DeferredItem<Item> MED_PLANET_GRASS;
	public static final DeferredItem<Item> PLANETARY_TREE_LOG;
	public static final DeferredItem<Item> PLANETARY_TREE_FOLIAGE;
	public static final DeferredItem<Item> UP_STEEL_STAIRCASE;
	public static final DeferredItem<Item> UP_WHITE_STAIRCASE;
	public static final DeferredItem<Item> UP_DARK_STAIRCASE;
	public static final DeferredItem<Item> SHUTTLE_WALL;
	public static final DeferredItem<Item> ARMORED_SHUTTLE_WALL;
	public static final DeferredItem<Item> DIRECTED_BASE_WINDOW;
	public static final DeferredItem<Item> RED_SCARF;
	public static final DeferredItem<Item> BLACK_SCARF;
	public static final DeferredItem<Item> BLACK_GREEN_SCARF;
	public static final DeferredItem<Item> BLUE_SCARF;
	public static final DeferredItem<Item> BROWN_SCARF;
	public static final DeferredItem<Item> GREEN_SCARF;
	public static final DeferredItem<Item> LIGHT_BLUE_SCARF;
	public static final DeferredItem<Item> LIGHT_BLUE_WHITE_SCARF;
	public static final DeferredItem<Item> ORANGE_SCARF;
	public static final DeferredItem<Item> PURPLE_SCARF;
	public static final DeferredItem<Item> SINDY_SCARF;
	public static final DeferredItem<Item> TRNS_SCARF;
	public static final DeferredItem<Item> YELLOW_SCARF;
	public static final DeferredItem<Item> ISOLATED_GLOVES;
	public static final DeferredItem<Item> PICK;
	public static final DeferredItem<Item> SECURITY_JUMPSUIT;
	public static final DeferredItem<Item> COMBAT_BOOTS_ITEM;
	public static final DeferredItem<Item> COMPUTER;
	public static final DeferredItem<Item> CLOSET_SECURE;
	public static final DeferredItem<Item> MAGNETIC_BOOTS_ITEM;
	public static final DeferredItem<Item> MAGNETIC_BOOTS_ACTIVE_ITEM;
	public static final DeferredItem<Item> PASSANGER_JUMPSUIT;
	public static final DeferredItem<Item> ATMOS_JUMPSUIT;
	public static final DeferredItem<Item> BOTANIST_JUMPSUIT;
	public static final DeferredItem<Item> CAPTAIN_JUMPSUIT;
	public static final DeferredItem<Item> CARGO_JUMPSUIT;
	public static final DeferredItem<Item> CE_JUMPSUIT;
	public static final DeferredItem<Item> CHEMIST_JUMPSUIT;
	public static final DeferredItem<Item> CMO_JUMPSUIT;
	public static final DeferredItem<Item> ENGENEER_JUMPSUIT;
	public static final DeferredItem<Item> HO_P_JUMPSUIT;
	public static final DeferredItem<Item> HO_S_JUMPSUIT;
	public static final DeferredItem<Item> MEDICAL_JUMPSUIT;
	public static final DeferredItem<Item> QM_JUMPSUIT;
	public static final DeferredItem<Item> RD_JUMPSUIT;
	public static final DeferredItem<Item> RND_JUMPSUIT;
	public static final DeferredItem<Item> WARDEN_JUMPSUIT;
	public static final DeferredItem<Item> BLACK_SOLES_ITEM;
	public static final DeferredItem<Item> CLOSET;
	public static final DeferredItem<Item> FENCE_LINE;
	public static final DeferredItem<Item> FENCE_G;
	public static final DeferredItem<Item> FENCE_POINT;
	public static final DeferredItem<Item> FENCE_P;
	public static final DeferredItem<Item> BRUTEPACK;
	public static final DeferredItem<Item> BLOODPACK;
	public static final DeferredItem<Item> GAUZE;
	public static final DeferredItem<Item> OINTMENT;
	public static final DeferredItem<Item> DEBUG_13;
	public static final DeferredItem<Item> DECAL_1SPAWNER;
	public static final DeferredItem<Item> DECAL_1DELETION;
	public static final DeferredItem<Item> CLOAKS_CAP;
	public static final DeferredItem<Item> MANTLES_CAP;
	public static final DeferredItem<Item> ARMOR_SECURITY;
	public static final DeferredItem<Item> HELMET_SECURITY;
	public static final DeferredItem<Item> BELT_SECURITY;
	public static final DeferredItem<Item> HEADSET_BASE;
	public static final DeferredItem<Item> PD_APASSANGER;
	public static final DeferredItem<Item> OUTERCLOTHING_EVA;
	public static final DeferredItem<Item> HELMETS_EVA;
	public static final DeferredItem<Item> EXTINGUISHER_CABINET;
	public static final DeferredItem<Item> EXTINGUISHER;
	public static final DeferredItem<Item> EXTINGUISHER_OPEN;
	public static final DeferredItem<Item> PEN;
	public static final DeferredItem<Item> RSU;
	public static final DeferredItem<Item> TITLE_STEEL_PAVEMENT_VERTICAL;
	public static final DeferredItem<Item> RC_DCARTRIDGE;
	static {
		ROD_FLOOR = block(Ssc14ModBlocks.ROD_FLOOR, new Item.Properties().stacksTo(1).fireResistant());
		ROOD = register("rood", RoodItem::new);
		SHEATHING = block(Ssc14ModBlocks.SHEATHING, new Item.Properties().stacksTo(1).fireResistant());
		STEEL = register("steel", SteelItem::new);
		PLASTEEL = register("plasteel", PlasteelItem::new);
		LOW_VOLTAGE_CABLE = register("low_voltage_cable", LowVoltageCableItem::new);
		MEDIUM_VOLTAGE_CABLE = register("medium_voltage_cable", MediumVoltageCableItem::new);
		HIGH_VOLTAGE_CABLE = register("high_voltage_cable", HighVoltageCableItem::new);
		CROWBAR = register("crowbar", ScrapItem::new);
		TITLE_STEEL = block(Ssc14ModBlocks.TITLE_STEEL, new Item.Properties().stacksTo(30).fireResistant());
		STEEL_WALL = block(Ssc14ModBlocks.STEEL_WALL, new Item.Properties().stacksTo(30).fireResistant());
		WALL_CARCASE = block(Ssc14ModBlocks.WALL_CARCASE, new Item.Properties().stacksTo(30).fireResistant());
		WELDING = register("welding", WeldingItem::new);
		ACTIVE_WELDER = register("active_welder", ActiveWelderItem::new);
		NIPPERS = register("nippers", NippersItem::new);
		FIRE_AXE = register("fire_axe", FireAxeItem::new);
		UPER_SHEATHING = block(Ssc14ModBlocks.UPER_SHEATHING, new Item.Properties().stacksTo(1).fireResistant());
		ROD_UP_FLOOR = block(Ssc14ModBlocks.ROD_UP_FLOOR, new Item.Properties().stacksTo(1).fireResistant());
		SCREWDRIVER = register("screwdriver", ScrewdriverItem::new);
		SPANNER = register("spanner", SpannerItem::new);
		BASE_AIRLOCK_D_1 = block(Ssc14ModBlocks.BASE_AIRLOCK_D_1, new Item.Properties().stacksTo(1).fireResistant());
		UP_TITLE = block(Ssc14ModBlocks.UP_TITLE, new Item.Properties().stacksTo(30).fireResistant());
		WALL_CARCASE_ENTIT_SPAWN_EGG = register("wall_carcase_entit_spawn_egg", properties -> new SpawnEggItem(Ssc14ModEntities.WALL_CARCASE_ENTIT.get(), properties));
		ID_CARD_PASSANGER = register("id_card_passanger", IDCardPassangerItem::new);
		CONSOLE_OF_ID = block(Ssc14ModBlocks.CONSOLE_OF_ID, new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON).fireResistant());
		ID_CONSOLE_ENTITY_SPAWN_EGG = register("id_console_entity_spawn_egg", properties -> new SpawnEggItem(Ssc14ModEntities.ID_CONSOLE_ENTITY.get(), properties));
		GAS_ANALYSER = register("gas_analyser", GasAnalyserItem::new);
		BASE_WINDOW = block(Ssc14ModBlocks.BASE_WINDOW, new Item.Properties().stacksTo(30).fireResistant());
		GLASS_SHARD = register("glass_shard", GlassShardItem::new);
		GLASS = register("glass", GlassItem::new);
		ACCESS_CONFIG = register("access_config", AccessConfigItem::new);
		ID_CARD_CAPITAN = register("id_card_capitan", IDCardCapitanItem::new);
		ID_CARD_PNT = register("id_card_pnt", IDCardPNTItem::new);
		ID_CARD_ADUTANT = register("id_card_adutant", IDCardAdutantItem::new);
		ID_CARD_AVD = register("id_card_avd", IDCardAVDItem::new);
		ID_CARD_OSH = register("id_card_osh", IDCardOSHItem::new);
		ID_CARD_MIME = register("id_card_mime", IDCardMimeItem::new);
		ID_CARD_CLOWN = register("id_card_clown", IDCardClownItem::new);
		ID_CARD_HO_P = register("id_card_ho_p", IDCardHoPItem::new);
		ID_CARD_SERVICE_W = register("id_card_service_w", IDCardServiceWItem::new);
		ID_CARD_CLEANER = register("id_card_cleaner", IDCardCleanerItem::new);
		ID_CARD_CHEF = register("id_card_chef", IDCardChefItem::new);
		ID_CARD_BOTANIK = register("id_card_botanik", IDCardBotanikItem::new);
		ID_CARD_BARMEN = register("id_card_barmen", IDCardBarmenItem::new);
		ID_CARD_PRIEST = register("id_card_priest", IDCardPriestItem::new);
		ID_CARD_QM = register("id_card_qm", IDCardQmItem::new);
		ID_CARD_UTILIZATOR = register("id_card_utilizator", IDCardUtilizatorItem::new);
		ID_CARD_LOADER = register("id_card_loader", IDCardLoaderItem::new);
		ID_CARD_REPORTER = register("id_card_reporter", IDCardReporterItem::new);
		ID_CARD_BOXER = register("id_card_boxer", IDCardBoxerItem::new);
		ID_CARD_BIBLIOTEKAR = register("id_card_bibliotekar", IDCardBibliotekarItem::new);
		ID_CARD_ZOOTECHNIK = register("id_card_zootechnik", IDCardZootechnikItem::new);
		ID_CARD_CE = register("id_card_ce", IDCardCEItem::new);
		ID_CARD_VE = register("id_card_ve", IDCardVEItem::new);
		ID_CARD_ATMOS = register("id_card_atmos", IDCardAtmosItem::new);
		ID_CARD_ENGENEER = register("id_card_engeneer", IDCardEngeneerItem::new);
		ID_CARD_TECH_ASSISTENT = register("id_card_tech_assistent", IDCardTechAssistentItem::new);
		ID_CARD_MUSICANT = register("id_card_musicant", IDCardMusicantItem::new);
		ID_CARD_HO_S = register("id_card_ho_s", IDCardHoSItem::new);
		ID_CARD_INSTRUCTOR_S = register("id_card_instructor_s", IDCardInstructorSItem::new);
		ID_CARD_WARD = register("id_card_ward", IDCardWardItem::new);
		ID_CARD_DETECTIVE = register("id_card_detective", IDCardDetectiveItem::new);
		ID_CARD_BRIG_MED = register("id_card_brig_med", IDCardBrigMedItem::new);
		ID_CARD_OFICER_S = register("id_card_oficer_s", IDCardOficerSItem::new);
		ID_CARD_KADET_S = register("id_card_kadet_s", IDCardKadetSItem::new);
		ID_CARD_CMO = register("id_card_cmo", IDCardCMOItem::new);
		ID_CARD_VM = register("id_card_vm", IDCardVMItem::new);
		ID_CARD_CHIMIC = register("id_card_chimic", IDCardChimicItem::new);
		ID_CARD_PARAMED = register("id_card_paramed", IDCardParamedItem::new);
		ID_CARD_MEDIC = register("id_card_medic", IDCardMedicItem::new);
		ID_CARD_PSIHOLOG = register("id_card_psiholog", IDCardPsihologItem::new);
		ID_CARD_INTERN = register("id_card_intern", IDCardInternItem::new);
		ID_CARD_RD = register("id_card_rd", IDCardRDItem::new);
		ID_CARD_VS = register("id_card_vs", IDCardVSItem::new);
		ID_CARD_SCIENTIST = register("id_card_scientist", IDCardScientistItem::new);
		ID_CARD_SCI_ASSISTENT = register("id_card_sci_assistent", IDCardSciAssistentItem::new);
		PORTABLE_SHEATER = block(Ssc14ModBlocks.PORTABLE_SHEATER, new Item.Properties().stacksTo(1));
		SILVER = register("silver", SilverItem::new);
		SSC_14_GOLD = register("ssc_14_gold", SSC14GoldItem::new);
		URAN = register("uran", UranItem::new);
		PLASMA = register("plasma", PlasmaItem::new);
		PLASTIC = register("plastic", PlasticItem::new);
		PLASTEEL_WALL = block(Ssc14ModBlocks.PLASTEEL_WALL, new Item.Properties().stacksTo(30).fireResistant());
		PLASTEEL_WALL_CARCASE = block(Ssc14ModBlocks.PLASTEEL_WALL_CARCASE, new Item.Properties().stacksTo(30).fireResistant());
		ENERGY_BAR = register("energy_bar", EnergyBarItem::new);
		ENERGY_BAR_TRASH = register("energy_bar_trash", EnergyBarTrashItem::new);
		ENERGY_BAR_2 = register("energy_bar_2", EnergyBar2Item::new);
		PLASSTEEL_WALL_CARCASE_ENTIT_SPAWN_EGG = register("plassteel_wall_carcase_entit_spawn_egg", properties -> new SpawnEggItem(Ssc14ModEntities.PLASSTEEL_WALL_CARCASE_ENTIT.get(), properties));
		TITLE_DARK = block(Ssc14ModBlocks.TITLE_DARK, new Item.Properties().stacksTo(30).fireResistant());
		AIRLOCK_CONTROLLER = register("airlock_controller", AirlockControllerItem::new);
		APC = block(Ssc14ModBlocks.APC, new Item.Properties().stacksTo(1).fireResistant());
		PODSTATION = block(Ssc14ModBlocks.PODSTATION, new Item.Properties().stacksTo(1).fireResistant());
		DEBU_GGENERATOR = block(Ssc14ModBlocks.DEBU_GGENERATOR, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC).fireResistant());
		LAMP = block(Ssc14ModBlocks.LAMP, new Item.Properties().stacksTo(1).fireResistant());
		TITLE_STEEL_DIAGONAL_MINI = block(Ssc14ModBlocks.TITLE_STEEL_DIAGONAL_MINI, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_DIAGONAL = block(Ssc14ModBlocks.TITLE_STEEL_DIAGONAL, new Item.Properties().stacksTo(30).fireResistant());
		UP_TITLE_STEEL = block(Ssc14ModBlocks.UP_TITLE_STEEL, new Item.Properties().stacksTo(30).fireResistant());
		UP_TITLE_DARK = block(Ssc14ModBlocks.UP_TITLE_DARK, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_MINI = block(Ssc14ModBlocks.TITLE_STEEL_MINI, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_MONO = block(Ssc14ModBlocks.TITLE_STEEL_MONO, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_OFFSET = block(Ssc14ModBlocks.TITLE_STEEL_OFFSET, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_PAVEMENT = block(Ssc14ModBlocks.TITLE_STEEL_PAVEMENT, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_STEEL_HERRINGBONE = block(Ssc14ModBlocks.TITLE_STEEL_HERRINGBONE, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_PLASTIC = block(Ssc14ModBlocks.TITLE_PLASTIC, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_DIAGONAL_MINI = block(Ssc14ModBlocks.TITLE_DARK_DIAGONAL_MINI, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_DIAGONAL = block(Ssc14ModBlocks.TITLE_DARK_DIAGONAL, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_MINI = block(Ssc14ModBlocks.TITLE_DARK_MINI, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_MONO = block(Ssc14ModBlocks.TITLE_DARK_MONO, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_OFFSET = block(Ssc14ModBlocks.TITLE_DARK_OFFSET, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_PAVEMENT = block(Ssc14ModBlocks.TITLE_DARK_PAVEMENT, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_PAVEMENT_VERTICAL = block(Ssc14ModBlocks.TITLE_DARK_PAVEMENT_VERTICAL, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_HERRINGBONE = block(Ssc14ModBlocks.TITLE_DARK_HERRINGBONE, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_DARK_PLASTIC = block(Ssc14ModBlocks.TITLE_DARK_PLASTIC, new Item.Properties().stacksTo(30).fireResistant());
		SMES = block(Ssc14ModBlocks.SMES, new Item.Properties().stacksTo(1).fireResistant());
		TECH_LAMP = block(Ssc14ModBlocks.TECH_LAMP, new Item.Properties().stacksTo(1).fireResistant());
		LED_LIGHT_TUBE = register("led_light_tube", LedLightTubeItem::new);
		LIGHT_BULB = register("light_bulb", LightBulbItem::new);
		LED_LIGHT_TUBE_BROKEN = register("led_light_tube_broken", LedLightTubeBrokenItem::new);
		LIGHT_BULB_BROKEN = register("light_bulb_broken", LightBulbBrokenItem::new);
		ARMORED_WINDOW = block(Ssc14ModBlocks.ARMORED_WINDOW, new Item.Properties().stacksTo(30).fireResistant());
		ARM_GLASS_SHARD = register("arm_glass_shard", ArmGlassShardItem::new);
		ARM_GLASS = register("arm_glass", ArmGlassItem::new);
		DEBUG_LAMP = block(Ssc14ModBlocks.DEBUG_LAMP, new Item.Properties().stacksTo(1).fireResistant());
		DEBUG_TECH_LAMP = block(Ssc14ModBlocks.DEBUG_TECH_LAMP, new Item.Properties().stacksTo(1).fireResistant());
		GRILLE = block(Ssc14ModBlocks.GRILLE, new Item.Properties().stacksTo(1).fireResistant());
		BROKEN_GRILLE = block(Ssc14ModBlocks.BROKEN_GRILLE, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_BASE = block(Ssc14ModBlocks.ASTEROID_STONE_BASE, new Item.Properties().stacksTo(1).fireResistant());
		RAW_IRON = register("raw_iron", RawIronItem::new);
		RAW_QUARTZ = register("raw_quartz", RawQuartzItem::new);
		ASTEROID_STONE_IRON = block(Ssc14ModBlocks.ASTEROID_STONE_IRON, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_QUARTZ = block(Ssc14ModBlocks.ASTEROID_STONE_QUARTZ, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_COAL = block(Ssc14ModBlocks.ASTEROID_STONE_COAL, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_GOLD = block(Ssc14ModBlocks.ASTEROID_STONE_GOLD, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_PLASMA = block(Ssc14ModBlocks.ASTEROID_STONE_PLASMA, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_SILVER = block(Ssc14ModBlocks.ASTEROID_STONE_SILVER, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_URAN = block(Ssc14ModBlocks.ASTEROID_STONE_URAN, new Item.Properties().stacksTo(1).fireResistant());
		ASTEROID_STONE_DIAMOND = block(Ssc14ModBlocks.ASTEROID_STONE_DIAMOND, new Item.Properties().stacksTo(1).fireResistant());
		RAW_COAL = register("raw_coal", RawCoalItem::new);
		RAW_GOLD = register("raw_gold", RawGoldItem::new);
		RAW_PLASMA = register("raw_plasma", RawPlasmaItem::new);
		RAW_SILVER = register("raw_silver", RawSilverItem::new);
		RAW_URAN = register("raw_uran", RawUranItem::new);
		RAW_DIAMOND = register("raw_diamond", RawDiamondItem::new);
		CAVE_FLOOR_1 = block(Ssc14ModBlocks.CAVE_FLOOR_1, new Item.Properties().stacksTo(1).fireResistant());
		GRAVITY_GENERATOR = block(Ssc14ModBlocks.GRAVITY_GENERATOR, new Item.Properties().stacksTo(1).fireResistant());
		TITLE_WHITE = block(Ssc14ModBlocks.TITLE_WHITE, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_DIAGONAL_MINI = block(Ssc14ModBlocks.TITLE_WHITE_DIAGONAL_MINI, new Item.Properties().stacksTo(30).fireResistant());
		CATWALK_FLOOR = block(Ssc14ModBlocks.CATWALK_FLOOR, new Item.Properties().stacksTo(1).fireResistant());
		TITLE_WHITE_DIAGONAL = block(Ssc14ModBlocks.TITLE_WHITE_DIAGONAL, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_HERRINGBONE = block(Ssc14ModBlocks.TITLE_WHITE_HERRINGBONE, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_MINI = block(Ssc14ModBlocks.TITLE_WHITE_MINI, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_MONO = block(Ssc14ModBlocks.TITLE_WHITE_MONO, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_OFFSET = block(Ssc14ModBlocks.TITLE_WHITE_OFFSET, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_PAVEMENT = block(Ssc14ModBlocks.TITLE_WHITE_PAVEMENT, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_PAVEMENT_VERTICAL = block(Ssc14ModBlocks.TITLE_WHITE_PAVEMENT_VERTICAL, new Item.Properties().stacksTo(30).fireResistant());
		TITLE_WHITE_PLASTIC = block(Ssc14ModBlocks.TITLE_WHITE_PLASTIC, new Item.Properties().stacksTo(30).fireResistant());
		C_4 = block(Ssc14ModBlocks.C_4, new Item.Properties().stacksTo(1));
		MACHINE_FRAME = block(Ssc14ModBlocks.MACHINE_FRAME, new Item.Properties().stacksTo(1));
		MACHINE_FRAME_2 = block(Ssc14ModBlocks.MACHINE_FRAME_2, new Item.Properties().stacksTo(1));
		CAPACITOR = register("capacitor", CapacitorItem::new);
		MATTER_BIN = register("matter_bin", MatterBinItem::new);
		MICRO_MANIPULATOR = register("micro_manipulator", MicroManipulatorItem::new);
		SUBSTATION_BOARD = register("substation_board", SubstationBoardItem::new);
		SMES_BOARD = register("smes_board", SMESBoardItem::new);
		APC_BOARD = register("apc_board", APCBoardItem::new);
		STEEL_TABLE = block(Ssc14ModBlocks.STEEL_TABLE, new Item.Properties().stacksTo(1));
		LOW_BATTERIE = register("low_batterie", LowBatterieItem::new);
		STEEL_STAIRCASE = block(Ssc14ModBlocks.STEEL_STAIRCASE, new Item.Properties().stacksTo(1));
		WHITE_STAIRCASE = block(Ssc14ModBlocks.WHITE_STAIRCASE, new Item.Properties().stacksTo(1));
		DARK_STAIRCASE = block(Ssc14ModBlocks.DARK_STAIRCASE, new Item.Properties().stacksTo(1));
		STEEL_CHAIR = block(Ssc14ModBlocks.STEEL_CHAIR, new Item.Properties().stacksTo(1));
		WOOD_CHAIR = block(Ssc14ModBlocks.WOOD_CHAIR, new Item.Properties().stacksTo(1));
		OFICE_BLACK_CHAIR = block(Ssc14ModBlocks.OFICE_BLACK_CHAIR, new Item.Properties().stacksTo(1));
		OFICE_WHITE_CHAIR = block(Ssc14ModBlocks.OFICE_WHITE_CHAIR, new Item.Properties().stacksTo(1));
		BAR_CHAIR = block(Ssc14ModBlocks.BAR_CHAIR, new Item.Properties().stacksTo(1));
		KOSTILNIBLOK = block(Ssc14ModBlocks.KOSTILNIBLOK, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC).fireResistant());
		DEBUG_GRAV_GEN = block(Ssc14ModBlocks.DEBUG_GRAV_GEN, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC).fireResistant());
		NUCLEAR_WARHEAD = block(Ssc14ModBlocks.NUCLEAR_WARHEAD, new Item.Properties().stacksTo(1));
		DIRT = block(Ssc14ModBlocks.DIRT, new Item.Properties().stacksTo(1));
		GRASS_LIGHT_BLOCK = block(Ssc14ModBlocks.GRASS_LIGHT_BLOCK, new Item.Properties().stacksTo(1));
		LOW_PLANET_GRASS = block(Ssc14ModBlocks.LOW_PLANET_GRASS, new Item.Properties().stacksTo(1));
		MED_PLANET_GRASS = block(Ssc14ModBlocks.MED_PLANET_GRASS, new Item.Properties().stacksTo(1));
		PLANETARY_TREE_LOG = block(Ssc14ModBlocks.PLANETARY_TREE_LOG, new Item.Properties().stacksTo(1));
		PLANETARY_TREE_FOLIAGE = block(Ssc14ModBlocks.PLANETARY_TREE_FOLIAGE, new Item.Properties().stacksTo(1));
		UP_STEEL_STAIRCASE = block(Ssc14ModBlocks.UP_STEEL_STAIRCASE, new Item.Properties().stacksTo(1));
		UP_WHITE_STAIRCASE = block(Ssc14ModBlocks.UP_WHITE_STAIRCASE, new Item.Properties().stacksTo(1));
		UP_DARK_STAIRCASE = block(Ssc14ModBlocks.UP_DARK_STAIRCASE, new Item.Properties().stacksTo(1));
		SHUTTLE_WALL = block(Ssc14ModBlocks.SHUTTLE_WALL, new Item.Properties().stacksTo(1).fireResistant());
		ARMORED_SHUTTLE_WALL = block(Ssc14ModBlocks.ARMORED_SHUTTLE_WALL, new Item.Properties().stacksTo(1).fireResistant());
		DIRECTED_BASE_WINDOW = block(Ssc14ModBlocks.DIRECTED_BASE_WINDOW, new Item.Properties().stacksTo(1).fireResistant());
		RED_SCARF = register("red_scarf", RedScarfItem::new);
		BLACK_SCARF = register("black_scarf", BlackScarfItem::new);
		BLACK_GREEN_SCARF = register("black_green_scarf", BlackGreenScarfItem::new);
		BLUE_SCARF = register("blue_scarf", BlueScarfItem::new);
		BROWN_SCARF = register("brown_scarf", BrownScarfItem::new);
		GREEN_SCARF = register("green_scarf", GreenScarfItem::new);
		LIGHT_BLUE_SCARF = register("light_blue_scarf", LightBlueScarfItem::new);
		LIGHT_BLUE_WHITE_SCARF = register("light_blue_white_scarf", LightBlueWhiteScarfItem::new);
		ORANGE_SCARF = register("orange_scarf", OrangeScarfItem::new);
		PURPLE_SCARF = register("purple_scarf", PurpleScarfItem::new);
		SINDY_SCARF = register("sindy_scarf", SindyScarfItem::new);
		TRNS_SCARF = register("trns_scarf", TrnsScarfItem::new);
		YELLOW_SCARF = register("yellow_scarf", YellowScarfItem::new);
		ISOLATED_GLOVES = register("isolated_gloves", IsolatedGlovesItem::new);
		PICK = register("pick", PickItem::new);
		SECURITY_JUMPSUIT = register("security_jumpsuit", SecurityJumpsuitItem::new);
		COMBAT_BOOTS_ITEM = register("combat_boots_item", CombatBootsItemItem::new);
		COMPUTER = block(Ssc14ModBlocks.COMPUTER, new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON).fireResistant());
		CLOSET_SECURE = block(Ssc14ModBlocks.CLOSET_SECURE, new Item.Properties().stacksTo(1).fireResistant());
		MAGNETIC_BOOTS_ITEM = register("magnetic_boots_item", MagneticBootsItemItem::new);
		MAGNETIC_BOOTS_ACTIVE_ITEM = register("magnetic_boots_active_item", MagneticBootsACTIVEItemItem::new);
		PASSANGER_JUMPSUIT = register("passanger_jumpsuit", PassangerJumpsuitItem::new);
		ATMOS_JUMPSUIT = register("atmos_jumpsuit", AtmosJumpsuitItem::new);
		BOTANIST_JUMPSUIT = register("botanist_jumpsuit", BotanistJumpsuitItem::new);
		CAPTAIN_JUMPSUIT = register("captain_jumpsuit", CaptainJumpsuitItem::new);
		CARGO_JUMPSUIT = register("cargo_jumpsuit", CargoJumpsuitItem::new);
		CE_JUMPSUIT = register("ce_jumpsuit", CEJumpsuitItem::new);
		CHEMIST_JUMPSUIT = register("chemist_jumpsuit", ChemistJumpsuitItem::new);
		CMO_JUMPSUIT = register("cmo_jumpsuit", CMOJumpsuitItem::new);
		ENGENEER_JUMPSUIT = register("engeneer_jumpsuit", EngeneerJumpsuitItem::new);
		HO_P_JUMPSUIT = register("ho_p_jumpsuit", HoPJumpsuitItem::new);
		HO_S_JUMPSUIT = register("ho_s_jumpsuit", HoSJumpsuitItem::new);
		MEDICAL_JUMPSUIT = register("medical_jumpsuit", MedicalJumpsuitItem::new);
		QM_JUMPSUIT = register("qm_jumpsuit", QMJumpsuitItem::new);
		RD_JUMPSUIT = register("rd_jumpsuit", RDJumpsuitItem::new);
		RND_JUMPSUIT = register("rnd_jumpsuit", RNDJumpsuitItem::new);
		WARDEN_JUMPSUIT = register("warden_jumpsuit", WardenJumpsuitItem::new);
		BLACK_SOLES_ITEM = register("black_soles_item", BlackSolesItemItem::new);
		CLOSET = block(Ssc14ModBlocks.CLOSET, new Item.Properties().stacksTo(1).fireResistant());
		FENCE_LINE = register("fence_line", properties -> new FenceLineBlock.Item(properties.stacksTo(1)));
		FENCE_G = register("fence_g", properties -> new FenceGBlock.Item(properties.stacksTo(1)));
		FENCE_POINT = register("fence_point", properties -> new FencePointBlock.Item(properties.stacksTo(1)));
		FENCE_P = register("fence_p", properties -> new FencePBlock.Item(properties.stacksTo(1)));
		BRUTEPACK = register("brutepack", BrutepackItem::new);
		BLOODPACK = register("bloodpack", BloodpackItem::new);
		GAUZE = register("gauze", GauzeItem::new);
		OINTMENT = register("ointment", OintmentItem::new);
		DEBUG_13 = block(Ssc14ModBlocks.DEBUG_13);
		DECAL_1SPAWNER = register("decal_1spawner", DECAL1spawnerItem::new);
		DECAL_1DELETION = register("decal_1deletion", DECAL1deletionItem::new);
		CLOAKS_CAP = register("cloaks_cap", CloaksCapItem::new);
		MANTLES_CAP = register("mantles_cap", MantlesCapItem::new);
		ARMOR_SECURITY = register("armor_security", ArmorSecurityItem::new);
		HELMET_SECURITY = register("helmet_security", HelmetSecurityItem::new);
		BELT_SECURITY = register("belt_security", BeltSecurityItem::new);
		HEADSET_BASE = register("headset_base", HeadsetBaseItem::new);
		PD_APASSANGER = register("pd_apassanger", PDApassangerItem::new);
		OUTERCLOTHING_EVA = register("outerclothing_eva", OuterclothingEvaItem::new);
		HELMETS_EVA = register("helmets_eva", HelmetsEvaItem::new);
		EXTINGUISHER_CABINET = block(Ssc14ModBlocks.EXTINGUISHER_CABINET, new Item.Properties().stacksTo(1));
		EXTINGUISHER = register("extinguisher", ExtinguisherItem::new);
		EXTINGUISHER_OPEN = register("extinguisher_open", ExtinguisherOpenItem::new);
		PEN = register("pen", PenItem::new);
		RSU = register("rsu", RSUItem::new);
		TITLE_STEEL_PAVEMENT_VERTICAL = block(Ssc14ModBlocks.TITLE_STEEL_PAVEMENT_VERTICAL, new Item.Properties().stacksTo(30).fireResistant());
		RC_DCARTRIDGE = register("rc_dcartridge", RCDcartridgeItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new AccessConfigInventoryCapability(stack), ACCESS_CONFIG.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new PDApassangerInventoryCapability(stack), PD_APASSANGER.get());
	}
}